name: Terraform Workflow

on:
  push:
    branches: [develop, main]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  terraform:
    runs-on: ubuntu-24.04
    # Expor o output para que o próximo job possa ler
    outputs:
      destroy: ${{ steps.read-destroy-config.outputs.destroy }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::368453405930:role/projeto-node-ec2-vpc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Read destroy configuration
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.${{ github.ref_name }}' ./infra/destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd infra && terraform init \
            -backend-config="bucket=ramonriserio-us-east-1-terraform-statefile" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=ramonriserio-us-east-1-terraform-lock"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform destroy -var-file="./envs/${{ github.ref_name }}/terraform.tfvars" -auto-approve

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform plan -var-file="./envs/${{ github.ref_name }}/terraform.tfvars" -out="${{ github.ref_name }}.plan"

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform apply "${{ github.ref_name }}.plan"

      - name: Wait for instance startup
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: |
          echo "⏳ Waiting 90s for instance and app startup..."
          sleep 90

  # Job que chama o Docker Workflow 
  call-docker-workflow:
    needs: terraform      # Só roda se o terraform acabar com sucesso
    # Só roda se NÃO foi um Destroy
    if: needs.terraform.outputs.destroy != 'true' && needs.terraform.result == 'success'
    uses: ./.github/workflows/app.yml     # Chama o arquivo do Docker workflow
    with:
      skip_infra_check: true    # Avisa o Docker para pular a checagem de infra
    secrets: inherit            # Passa todos os secrets (AWS, DOCKER, SSH) automaticamente