name: Terraform Workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::368453405930:role/projeto-node-ec2-vpc
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Read destroy configuration
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.${{ github.ref_name }}' ./infra/destroy_config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd infra && terraform init \
            -backend-config="bucket=ramonriserio-us-east-1-terraform-statefile" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=ramonriserio-us-east-1-terraform-lock"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform destroy -var-file="./envs/${{ github.ref_name }}/terraform.tfvars" -auto-approve

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform plan -var-file="./envs/${{ github.ref_name }}/terraform.tfvars" -out="${{ github.ref_name }}.plan"

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: cd infra &&
          terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }} &&
          terraform apply "${{ github.ref_name }}.plan"

      - name: Wait for instance startup
        if: steps.read-destroy-config.outputs.destroy != 'true'
        run: |
          echo "⏳ Waiting 90s for instance and app startup..."
          sleep 90

      - name: Fetch Public IP
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: ec2_ip
        run: cd infra &&
          PUBLIC_IP=$(terraform output -raw public_ip) &&
          echo "$PUBLIC_IP" > public_ip.txt

      - name: Upload Public IP Artifact      # Permitirá garantir que o Terraform Workflow seja sempre
        uses: actions/upload-artifact@v4      # executado antes do Docker Workflow
        with:
          name: public_ip
          path: infra/public_ip.txt                 # Esse arquivo foi criado no step Fetch Public IP e
                                              # será baixado no Docker Workflow
